DiscourseMountableSso.configuration.secret = "83IC~q<ITI#15n(6f515sw5crA?lF&"
DiscourseMountableSso.configuration.discourse_url = "http://localhost:3020/"	
DiscourseMountableSso.configuration.login_path = "/login"
DiscourseMountableSso.configuration.discourse_data_method = "get_discourse_data"
DiscourseMountableSso.configuration.logged_in_check_method = "logged_in?"
DiscourseMountableSso.configuration.store_return_to_url_method = "return_to_url"