DiscourseMountableSso.configuration.secret = "83IC~q<ITI#15n(6f515sw5crA?lF&"
DiscourseMountableSso.configuration.your_discourse_url = "http://local:3000/"	
DiscourseMountableSso.configuration.your_server_login_path = "/login"	
DiscourseMountableSso.configuration.your_discourse_data_method = "get_discourse_data"
DiscourseMountableSso.configuration.your_check_logged_in_method = "logged_in?"
DiscourseMountableSso.configuration.your_return_to_url = "return_to_url"